import numpy as np
a = np.array(np.arange(10))
b = np.array([2,3,5,7,11,15])
c = np.concatenate((a, b))
d = np.array([[1, 2], [3, 4]])
e = np.array([[5, 6], [7, 8]])
f = np.concatenate((d, e))
print("Neues Format von {} : {}\n".format(a,a.reshape(2,5)))
print("Neues Format von {} : {}\n".format(d,d.reshape(4)))
print("Neues Format von {} : {}\n".format(f,f.reshape(8)))
x = np.arange(1, 25).reshape(2, 12)
y = np.arange(1, 50).reshape(7, 7)
print("x: ",x,"\n")
print("y: ",y,"\n")
